-- M1_LENS_CATALOG_SEED_FROM_EXCEL — 02_designs.sql
-- Idempotent UPSERT of global lens_design rows.
-- Uses (name, brand_id, owner_tenant_id) UNIQUE NULLS NOT DISTINCT.

WITH ins(brand_name, design_name, lens_type, product_type) AS (
  VALUES
    ('Color Flex', 'מדף', 'single_vision', 'glasses'),
    ('Core Line', 'מדף', 'single_vision', 'glasses'),
    ('Leica', 'Variovid 2', 'progressive', 'glasses'),
    ('Leica', 'Variovid 3', 'progressive', 'glasses'),
    ('Leica', 'Variovid 4', 'progressive', 'glasses'),
    ('Rodenstock', 'Ergo', 'office', 'glasses'),
    ('Rodenstock', 'Impression B.I.G', 'progressive', 'glasses'),
    ('Rodenstock', 'LifeStandard', 'progressive', 'glasses'),
    ('Rodenstock', 'Multigressive B.I.G', 'progressive', 'glasses'),
    ('Rodenstock', 'NetLine', 'office', 'glasses'),
    ('Hoya', 'Amplitude', 'occupational', 'glasses'),
    ('Hoya', 'BALANSIS', 'occupational', 'glasses'),
    ('Hoya', 'LifeStyle4', 'progressive', 'glasses'),
    ('Hoya', 'MyoSmart', 'progressive', 'glasses'),
    ('Hoya', 'MySelf Individual', 'progressive', 'glasses'),
    ('Hoya', 'אור כחול', 'single_vision', 'glasses'),
    ('Hoya', 'מדף', 'single_vision', 'glasses'),
    ('Hoya', 'מחליף צבע', 'single_vision', 'glasses'),
    ('אופטימייז', 'BiFocal', 'bifocal', 'glasses'),
    ('אופטימייז', 'FIT', 'office', 'glasses'),
    ('אופטימייז', 'IPL', 'office', 'glasses'),
    ('אופטימייז', 'MyoSlow', 'progressive', 'glasses'),
    ('אופטימייז', 'Stepper', 'progressive', 'glasses'),
    ('אופטימייז', 'Superior', 'progressive', 'glasses'),
    ('אופטימייז', 'Top Office', 'office', 'glasses'),
    ('אופטימייז', 'אור כחול', 'single_vision', 'glasses'),
    ('אופטימייז', 'זכוכית חו"ל', 'single_vision', 'glasses'),
    ('אופטימייז', 'חד מוקדי', 'single_vision', 'glasses'),
    ('אופטימייז', 'מדף', 'single_vision', 'glasses'),
    ('אופטימייז', 'מחליף צבע', 'single_vision', 'glasses'),
    ('אופטימייז', 'צבע', 'single_vision', 'glasses'),
    ('יומיות', 'I CONTACT PRO', 'soft_contact', 'contact_lens'),
    ('יומיות', 'Total1', 'single_vision', 'glasses'),
    ('שמיר', 'Invisible', 'single_vision', 'glasses'),
    ('שמיר', 'Kids', 'single_vision', 'glasses'),
    ('שמיר', 'Office', 'office', 'glasses'),
    ('שמיר', 'Premium 7', 'progressive', 'glasses'),
    ('שמיר', 'Premium 8', 'progressive', 'glasses'),
    ('שמיר', 'Premium 9', 'progressive', 'glasses'),
    ('שמיר', 'Regular', 'single_vision', 'glasses'),
    ('שמיר', 'אור כחול', 'soft_contact', 'contact_lens'),
    ('שמיר', 'חד מוקדי', 'single_vision', 'glasses'),
    ('שמיר', 'מדף', 'soft_contact', 'contact_lens'),
    ('שמיר', 'מחליף צבע', 'single_vision', 'contact_lens'),
    ('שמיר', 'צבע', 'single_vision', 'glasses'),
    ('חודשיות', 'AIROPTIC', 'single_vision', 'glasses'),
    ('חודשיות', 'AirOptix Hydraglyde Multi', 'soft_contact', 'contact_lens'),
    ('חודשיות', 'Aqua 6pcs', 'single_vision', 'glasses'),
    ('חודשיות', 'Aqua Toric', 'single_vision', 'glasses'),
    ('חודשיות', 'Night&Day', 'single_vision', 'glasses'),
    ('חודשיות', 'Total30', 'single_vision', 'glasses'),
    ('יומיות', 'Aqua 30pcs', 'single_vision', 'glasses'),
    ('יומיות', 'Aqua 90pcs', 'single_vision', 'glasses'),
    ('יומיות', 'Aqua Toric 30pcs', 'single_vision', 'glasses'),
    ('יומיות', 'Total1 - Astigmatism', 'single_vision', 'glasses'),
    ('יומיות', 'Total1 Multifocal', 'single_vision', 'glasses'),
    ('יומיות', 'Total1 Toric', 'single_vision', 'glasses'),
    ('צייס', 'Individual 3', 'progressive', 'glasses'),
    ('צייס', 'Light 3D', 'progressive', 'glasses'),
    ('צייס', 'MyoCare', 'progressive', 'glasses'),
    ('צייס', 'MyoCareS', 'progressive', 'glasses'),
    ('צייס', 'Office Individual', 'office', 'glasses'),
    ('צייס', 'Office Plus', 'office', 'glasses'),
    ('צייס', 'Office Superb', 'office', 'glasses'),
    ('צייס', 'SuperB', 'progressive', 'glasses'),
    ('צייס', 'אור כחול', 'single_vision', 'glasses'),
    ('צייס', 'חד מוקדי', 'single_vision', 'glasses'),
    ('צייס', 'מדף', 'single_vision', 'glasses'),
    ('צייס', 'מחליף צבע', 'single_vision', 'glasses'),
    ('חודשיות', 'ביו דיספו', 'soft_contact', 'contact_lens'),
    ('חודשיות', 'ביו דיספו טוריק - 3 יח''', 'soft_contact', 'contact_lens'),
    ('חודשיות', 'ביו דיספו טוריק - 6 יח''', 'soft_contact', 'contact_lens'),
    ('חודשיות', 'ביומדיקס', 'soft_contact', 'contact_lens'),
    ('חודשיות', 'ביומדיקס טוריק', 'soft_contact', 'contact_lens'),
    ('חודשיות', 'דיספו פלוס', 'single_vision', 'contact_lens'),
    ('חודשיות', 'דיספו פלוס טוריק', 'soft_contact', 'contact_lens'),
    ('חודשיות', 'פרוקליר', 'soft_contact', 'contact_lens'),
    ('חודשיות', 'צבעוניות', 'soft_contact', 'contact_lens'),
    ('יומיות', 'ביומדיקס', 'soft_contact', 'contact_lens'),
    ('יומיות', 'ביומדיקס טוריק', 'soft_contact', 'contact_lens'),
    ('יומיות', 'דיספו BIO', 'soft_contact', 'contact_lens'),
    ('יומיות', 'דיספו BIO טוריק', 'soft_contact', 'contact_lens'),
    ('יומיות', 'קלריטי', 'soft_contact', 'contact_lens'),
    ('יומיות', 'קלריטי 90', 'soft_contact', 'contact_lens'),
    ('יומיות', 'קלריטי טוריק', 'soft_contact', 'contact_lens'),
    ('שנתיות', 'קבועות', 'soft_contact', 'contact_lens'),
    ('שנתיות', 'קבועות טוריות', 'soft_contact', 'contact_lens'),
    ('שנתיות', 'קשות', 'hard_contact', 'contact_lens'),
    ('שמיר', 'Autograph Intelligence', 'progressive', 'glasses'),
    ('שמיר', 'Autograph Prime 2', 'progressive', 'glasses'),
    ('שמיר', 'Spectrum+', 'progressive', 'glasses')
)
INSERT INTO lens_design (name, brand_id, lens_type, product_type, owner_tenant_id, is_published, lifecycle_status, is_deleted)
SELECT ins.design_name, b.id, ins.lens_type, ins.product_type, NULL, true, 'active'::text, false
FROM ins
JOIN lens_brand b ON b.name = ins.brand_name AND b.owner_tenant_id IS NULL
ON CONFLICT (name, brand_id, owner_tenant_id) DO UPDATE SET updated_at=now(), lens_type=EXCLUDED.lens_type;
