import "@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// ============================================================
// unsubscribe — Edge Function for one-click list removal
// Module 4 CRM — Go-Live P10 (2026-04-23)
// ============================================================
// Flow: GET ?token=<b64url(payload).b64url(sig)> →
//       verify HMAC → check expiry → UPDATE crm_leads
//       SET unsubscribed_at = now() → return HTML page.
//
// Token format (generated by send-message EF):
//   payload = `${lead_id}:${tenant_id}:${expiry_epoch}`
//   token   = b64url(payload) + "." + b64url(HMAC-SHA256(SERVICE_ROLE_KEY, payload))
//
// verify_jwt is false because the caller is an end-user's mail
// client following a link; the HMAC signature IS the auth.
// ============================================================

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
};

// --- base64url (no padding) ---

function b64urlDecode(s: string): Uint8Array {
  const pad = s.length % 4;
  const padded = s + (pad === 0 ? "" : "=".repeat(4 - pad));
  const bin = atob(padded.replace(/-/g, "+").replace(/_/g, "/"));
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

// --- HMAC ---

async function hmacSha256(keyStr: string, msg: string): Promise<Uint8Array> {
  const enc = new TextEncoder();
  const cryptoKey = await crypto.subtle.importKey(
    "raw",
    enc.encode(keyStr),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", cryptoKey, enc.encode(msg));
  return new Uint8Array(sig);
}

function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

// --- Token verification ---

type TokenPayload = { leadId: string; tenantId: string; exp: number };

async function verifyToken(token: string): Promise<TokenPayload | null> {
  const parts = token.split(".");
  if (parts.length !== 2) return null;
  let payloadBytes: Uint8Array;
  let providedSig: Uint8Array;
  try {
    payloadBytes = b64urlDecode(parts[0]);
    providedSig = b64urlDecode(parts[1]);
  } catch {
    return null;
  }
  const payload = new TextDecoder().decode(payloadBytes);
  const expectedSig = await hmacSha256(SERVICE_ROLE_KEY, payload);
  if (!timingSafeEqual(providedSig, expectedSig)) return null;

  const [leadId, tenantId, expStr] = payload.split(":");
  if (!leadId || !tenantId || !expStr) return null;
  const exp = Number.parseInt(expStr, 10);
  if (!Number.isFinite(exp)) return null;
  if (exp < Math.floor(Date.now() / 1000)) return null;
  return { leadId, tenantId, exp };
}

// --- HTML page helper ---

function htmlPage(titleHe: string, bodyHe: string, status: number): Response {
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const html = `<!DOCTYPE html>
<html lang="he" dir="rtl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(titleHe)}</title>
<style>
body { font-family: 'Heebo', 'Arial', sans-serif; background:#f8fafc; color:#1e293b;
  display:flex; align-items:center; justify-content:center; min-height:100vh; margin:0; }
.card { background:white; border:1px solid #e2e8f0; border-radius:16px; padding:48px 32px;
  max-width:480px; text-align:center; box-shadow:0 4px 24px rgba(15,23,42,.06); }
h1 { font-size:22px; margin:0 0 12px; color:#0f172a; }
p { font-size:15px; line-height:1.6; color:#475569; margin:0; }
</style>
</head>
<body>
<div class="card">
<h1>${esc(titleHe)}</h1>
<p>${esc(bodyHe)}</p>
</div>
</body>
</html>`;
  return new Response(html, {
    status,
    headers: { ...corsHeaders, "Content-Type": "text/html; charset=utf-8" },
  });
}

// --- Main handler ---

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const url = new URL(req.url);
  const token = url.searchParams.get("token");
  if (!token) {
    return htmlPage(
      "קישור לא תקין",
      "הקישור להסרה חסר — לא ניתן לעבד את הבקשה.",
      400,
    );
  }

  const parsed = await verifyToken(token);
  if (!parsed) {
    return htmlPage(
      "קישור לא תקין או שפג תוקפו",
      "לא ניתן לאמת את הקישור. ייתכן שהקישור שונה, פג תוקפו, או נוצר במערכת אחרת.",
      400,
    );
  }

  const db = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const { data, error } = await db
    .from("crm_leads")
    .update({
      unsubscribed_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })
    .eq("id", parsed.leadId)
    .eq("tenant_id", parsed.tenantId)
    .select("id, full_name")
    .maybeSingle();

  if (error) {
    console.error("unsubscribe update failed:", error);
    return htmlPage(
      "שגיאה זמנית",
      "לא הצלחנו לעבד את הבקשה כעת. אנא נסה שוב מאוחר יותר.",
      500,
    );
  }
  if (!data) {
    return htmlPage(
      "קישור לא תקין",
      "לא נמצא מנוי מתאים. ייתכן שכבר הוסר בעבר.",
      404,
    );
  }

  return htmlPage(
    "הוסרת מרשימת התפוצה בהצלחה",
    "הסרנו אותך מרשימת ההתראות. ניתן לסגור חלון זה.",
    200,
  );
});
