-- ═══════════════════════════════════════════════════════════════
-- GLOBAL SCHEMA — Optic Up
-- Reconciled from live DB: 2026-04-11 (Phase 3A Part 2)
-- Sources: modules/Module 3.1 - Project Reconstruction/db-audit/
--            01-tables.md     — 84 base tables (snapshot 2026-04-11; live count 113 as of 2026-05-09)
--            02-columns.md    — column-level detail (base tables + view columns)
--            03-views.md      — 24 views with full definitions
--            04-policies.md   — 162 RLS policies
--            05-functions.md  — 72 functions (41 project + 31 extension)
--            06-sequences.md  — 0 sequences (by design — UUID + RPC)
--
-- AUTHORITATIVE for table / view / policy / function declarations.
-- Per-module db-schema.sql files reference THIS file, not the reverse.
--
-- This file is a MAP. Column types, defaults, CHECK constraints, and full
-- policy / function / view bodies live in the db-audit/*.md source files.
-- Do not duplicate that content here — keep this file scannable.
--
-- Prior version: 2026-03-24 snapshot, stale at table level (missing 24 tables,
-- missing all 24 views, missing the AI content / translation / storefront CMS
-- surface). Backed up under
-- modules/Module 3.1 - Project Reconstruction/backups/M3.1-3A_2026-04-11/.
-- ═══════════════════════════════════════════════════════════════


-- ============================================================
-- CONVENTIONS — read this before adding or changing anything
-- ============================================================
--
-- TENANT ISOLATION — three RLS idioms exist in the live DB today:
--
--   Pattern 1 — JWT claim                   (STANDARD — ~140 policies)
--     (tenant_id = (((current_setting('request.jwt.claims', true))::json
--                    ->> 'tenant_id'))::uuid)
--     Used by every table in Modules 1, 1.5, 2, and most of Module 3.
--     All NEW tables MUST use this pattern.
--
--   Pattern 2 — Postgres session variable   (LEGACY — migrate to Pattern 1)
--     (tenant_id = (current_setting('app.tenant_id', true))::uuid)
--     Currently used by: media_library, campaigns, campaign_templates,
--                        supplier_balance_adjustments.
--     Functional, but inconsistent with the rest of the codebase.
--     Migration tracked in MASTER_ROADMAP.md (Module 3 Phase B preamble).
--
--   Pattern 3 — auth.uid() as tenant_id     (BUG — do not copy)
--     Currently used by: brand_content_log, storefront_component_presets,
--                        storefront_page_tags.
--     auth.uid() returns the authenticated USER uuid, not the tenant uuid,
--     so every signed-in user becomes their own "tenant" on these tables.
--     Works today only because service_role bypasses RLS on every write.
--     See SECURITY-FINDING block under RLS POLICIES below.
--
-- EVERY NEW TABLE MUST:
--   - have tenant_id UUID NOT NULL REFERENCES tenants(id)    (Iron Rule #14)
--   - have ENABLE ROW LEVEL SECURITY                          (Iron Rule #15)
--   - use Pattern 1 for its tenant_isolation policy
--   - carry tenant_id in every UNIQUE constraint               (Iron Rule #18)
--
-- PRIMARY KEYS — UUID everywhere (gen_random_uuid() or uuid_generate_v4()).
-- Sequential numbers (PO / return / box / internal doc) are generated by
-- SECURITY DEFINER RPCs, not by Postgres sequences (Iron Rule #13).
-- See FUNCTIONS and SEQUENCES sections below.
--
-- EXTENSIONS REQUIRED — uuid-ossp, pg_trgm.


-- ============================================================
-- TABLES (113 total live; 84 in initial reconstruction snapshot — see db-audit/01-tables.md, grouped by owning module)
-- Full column lists live in db-audit/02-columns.md.
-- Every table has rls_enabled=true (see db-audit/01-tables.md).
-- ============================================================

-- ------------------------------------------------------------
-- Module 1 — Inventory Management / Core ERP (36 tables)
-- ------------------------------------------------------------
-- Catalog, purchasing, receiving, sales sync, debt tracking, OCR, shipments.

--   Brands & catalog:
--     brands, inventory, inventory_images, inventory_logs,
--     suppliers, supplier_documents, supplier_document_files,
--     supplier_ocr_templates, supplier_payments, supplier_returns,
--     supplier_return_items, supplier_balance_adjustments
--
--   Purchasing & receiving:
--     purchase_orders, purchase_order_items,
--     goods_receipts, goods_receipt_items,
--     document_types, document_links, payment_methods, payment_allocations,
--     prepaid_deals, prepaid_checks, expense_folders
--     (currencies moved to GLOBALS block below — see "Global reference tables")
--
--   Global reference tables (Iron Rule 14 documented exception — universal data,
--   identical for every tenant; RLS read-anywhere + writes gated on
--   is_platform_super_admin()):
--     currencies — ISO-4217 codes (M1A-DEBT-01 hotfix 2026-05-14: PK on `code`,
--                  6 columns: code, name_he, symbol, decimal_digits, is_active, created_at;
--                  seeded ILS/USD/EUR; see modules/Module 1 - Inventory Management/
--                  docs/specs/M1A_CURRENCIES_GLOBAL_HOTFIX/)
--     (vat_rates is similar but documented under M1 Lens Phase 1A below)
--
--   Sync & stock counting:
--     sync_log, pending_sales, watcher_heartbeat,
--     stock_counts, stock_count_items
--
--   AI agent + OCR + alerts:
--     ai_agent_config, ocr_extractions, alerts, weekly_reports
--
--   Shipments (Phase 5.9):
--     courier_companies, shipments, shipment_items
--
--   M1 Lens Inventory (Phase 1A — added 2026-05-14, 17 new tables + 9 RPCs + 1 trigger + 1 view):
--     Catalog (platform-owned, owner_tenant_id NULL today):
--       lens_brand, lens_design, lens_variant, supplier_brand_distribution
--     Commercial:
--       supplier_catalog_offering, pricing_overlay,
--       vat_rates (GLOBAL — Iron Rule 14 documented exception, seeded with Israel 18%)
--     Retailer:
--       tenant_location, tenant_active_offerings, tenant_lens_stock
--     Operations (FIFO + receipts):
--       stock_lot, stock_movement, stock_transfer,
--       purchase_receipt, purchase_receipt_line  (NEW lens flow per Q1 option (c) divergence
--                                                  — frames keep legacy goods_receipts)
--     Governance:
--       supplier_permissions, change_approval_log
--     Sequence-state:
--       lens_variant_display_seq (singleton, scope='global'; powers next_lens_variant_display_id RPC)
--     M9 contract durability:
--       pending_lens_advancement_queue (K3 trigger enqueues here; M9 consumes when built)
--
--   M1 Lens Phase 1A FUNCTIONS (9 atomic RPCs + 1 trigger function — see FUNCTIONS section):
--     Sequential generators: next_lens_variant_display_id, next_lot_number,
--                             next_transfer_number, next_receipt_number
--     Ledger atomics:        record_stock_movement (FOR UPDATE on lot),
--                             record_transfer (parent + 2 children + dest lot),
--                             record_adjustment_found (creates lot + movement)
--     Pricing resolver:      effective_price (overlays in application_order + VAT)
--     K2 contract:           m1_create_receipt_from_box (orchestrator;
--                             auto-fires K3 trigger when sale_order_id present)
--     K3 trigger fn:         m9_lens_received_for_sale_order_trg_fn
--                             (AFTER INSERT on stock_movement → pending_lens_advancement_queue)
--   M1 Lens Phase 1A VIEWS:
--     v_suppliers_for_m9 (K5 contract; security_invoker=on; read-only for M9)
--
--   M1 Lens — DB Schema Receipts & Notes deltas (added 2026-05-17 by
--   SPEC M1_LENS_DB_SCHEMA_RECEIPTS_NOTES):
--     - purchase_receipt.has_no_invoice BOOLEAN NOT NULL DEFAULT FALSE
--       (Brief decision #14 — bookkeeper Invoices Inbox flag)
--     - lens_variant_notes (new tenant-scoped table, RLS canonical pattern;
--       backs Pricing screen לוגים+הערות drawer per Brief decision #18)

-- ------------------------------------------------------------
-- Module 1.5 — Shared Components (14 tables)
-- ------------------------------------------------------------
-- Multi-tenant identity, auth, messaging, knowledge, activity audit.

--   Tenancy & employees:
--     tenants, employees
--
--   Auth & permissions:
--     roles, permissions, role_permissions, employee_roles, auth_sessions
--
--   Activity / audit:
--     activity_log
--
--   Messaging & knowledge:
--     conversations, conversation_participants, messages, message_reactions,
--     knowledge_base, notification_preferences

-- ------------------------------------------------------------
-- Module 2 — Platform Admin (5 tables)
-- ------------------------------------------------------------
-- Super-admin control plane over all tenants.

--   plans, platform_admins, platform_audit_log,
--   tenant_config, tenant_provisioning_log
--
-- plans.features JSONB — 21 feature keys as of 2026-04-15:
--   Core ERP: inventory, purchasing, goods_receipts, supplier_debt, stock_count,
--             shipments, ocr, whatsapp, ai_alerts, access_sync
--   Storefront: storefront, image_studio, white_label, custom_domain
--   CMS/Studio (added 2026-04-15, migration 067):
--     cms_studio (true: premium+enterprise)
--     cms_custom_blocks (true: enterprise only)
--     cms_landing_pages (true: enterprise only)
--     cms_ai_tools (true: enterprise only)
--   API/Integration: api_access, b2b_marketplace, advanced_reports
-- Full reference: modules/Module 1.5 - Shared Components/docs/plans-features-reference.md

-- ------------------------------------------------------------
-- Module 3 — Storefront (25 tables, in opticup-storefront repo at runtime)
-- ------------------------------------------------------------
-- CMS, campaigns, AI content, translations, media library, leads.
--
-- NOTE: the ERP repo owns these DEFINITIONS (this file + db-audit),
-- but the CONSUMER code lives in the sibling repo opticup-storefront.
-- Storefront consumers read via Views + RPC only (Iron Rules #13, #24).

--   Storefront CMS:
--     storefront_pages, storefront_config, storefront_leads,
--     storefront_block_templates, storefront_components,
--     storefront_component_presets, storefront_templates,
--     storefront_page_tags, storefront_reviews
--
--   CMS + campaigns + media:
--     cms_leads, media_library, blog_posts,
--     campaigns, campaign_templates, brand_content_log
--
--   AI content & SEO:
--     ai_content, ai_content_corrections, content_performance,
--     content_versions, seo_targets
--
--   Translation system:
--     content_translations, translation_memory, translation_glossary,
--     translation_corrections, tenant_i18n_overrides

-- ------------------------------------------------------------
-- Module 4 — CRM (28 tables)
-- ------------------------------------------------------------
-- Lead → registration → event-day pipeline with messaging hub + automation engine.
-- Module 4 entered MAINTENANCE phase 2026-05-06; all 4 audit CRITICALs CLOSED.
--
--   Lead pipeline (8):
--     crm_leads, crm_lead_notes, crm_lead_tags, crm_tags,
--     crm_unsubscribes, crm_custom_field_defs, crm_custom_field_vals,
--     crm_field_visibility
--
--   Events (4):
--     crm_events, crm_event_attendees, crm_event_status_history,
--     crm_campaigns
--
--   Messaging (4):
--     crm_message_templates, crm_message_log, crm_message_queue,
--     crm_broadcasts
--
--   Automation (2):
--     crm_automation_rules, crm_automation_runs
--
--   Status / labels (2):
--     crm_statuses, crm_audit_log
--
--   Campaign analytics (5):
--     crm_campaign_pages, crm_facebook_campaigns, crm_ad_spend,
--     crm_cx_surveys, crm_unit_economics
--
--   Storefront ingress (2):
--     cms_leads (legacy WP-shortcode form, retired 2026-05-03 cutover),
--     short_links (HMAC-wrapped /r/<code> redirects)
--
--   Admin tooling (1):
--     crm_monday_column_map (one-time Monday board → tenant_id mapping)
--
-- RLS pattern (post-M4_TENANT_ISOLATION_HARDENING_PART1 + PART2, 2026-05-06):
--   Every M4 table has RLS enabled with the canonical 2-policy pattern:
--   service_bypass (service_role) + tenant_isolation (public, JWT-claim USING
--   per Iron Rule 15). cms_leads policy migrated to canonical pattern in PART1.
--   The 7 v_crm_* views run with security_invoker=on (PART1) so RLS on
--   underlying tables applies when queried from authenticated context.
--
-- RPC EXECUTE access (post-PART2, 2026-05-06):
--   anon+auth+service:    register_lead_to_event, submit_storefront_lead,
--                          verify_campaign_page_password (3 public ingress)
--   auth+service only:    check_in_attendee, move_attendee_between_events,
--                          transfer_credit_to_new_attendee, next_crm_event_number,
--                          restore_event_from_log, soft_delete_event_if_empty,
--                          sync_lead_status_from_attendee (7 staff actions)
--   service only:         cascade_attendee_soft_delete (DB trigger),
--                          import_leads_from_monday (admin) (2 internal)
--
-- Tenant config (2026-05-06 M4_HARDCODED_PRIZMA_REMOVAL):
--   tenants.business_phone + tenants.business_address columns populated.
--   tenants.ui_config JSONB extended with: whatsapp_phone_e164,
--   support_phone_display, storefront_url, brand{gold/_light/_hover}.
--   Replaces previously-hardcoded Prizma values across 5 source files +
--   3 EFs. SaaS-readiness: tenant 2 onboarding requires only DB rows.
--
-- Test-mode allowlists on tenants (2 channels, 2 storage shapes):
--   tenants.test_mode_sms_allowlist  jsonb         (top-level column, C001 2026-05-03)
--   tenants.ui_config.test_mode_email_allowlist  jsonb path (DEMO_EMAIL_ALLOWLIST_INFRA 2026-05-11)
--   Both store a jsonb array of strings; both are read by send-message EF
--   (functions/send-message/allowlists.ts). Contract per channel:
--     - Empty / NULL allowlist  → return true  (production mode; send to all)
--     - Non-empty array          → recipient must match an entry; else send is dropped
--                                  with status='rejected' in crm_message_log
--     - DB lookup error / non-array allowlist → fail-CLOSED (return false)
--   SMS comparison: phone normalization (E.164 ↔ Israeli local) per normalizePhone.
--   Email comparison: case-insensitive + whitespace-trimmed per normalizeEmail.
--   Demo tenant: 3 phones + 3 emails configured. Prizma tenant: both keys absent
--   (= production mode for both channels).
--   SMS uses a dedicated column because it predates ui_config; new test-mode
--   allowlists (email, future channels) live under ui_config so SaaS-tenant
--   onboarding requires only ui_config edits, no schema changes.
--
-- Module 4 schema authoritative file:
--   modules/Module 4 - CRM/docs/db-schema.sql (currently documents only the
--   payment-lifecycle additions per M4_ATTENDEE_PAYMENT_SCHEMA + 3 cycle
--   migrations from 2026-05-06; full 28-table reconstruction deferred to a
--   future Sentinel-tracked SPEC).

-- ------------------------------------------------------------
-- Pre-multitenancy (4 tables) — SECURITY DEBT
-- ------------------------------------------------------------
-- customers, prescriptions, sales, work_orders
--
-- ╔══════════════════════════════════════════════════════════╗
-- ║ SECURITY-FINDING #1 — ANON READ/WRITE ON 4 LEGACY TABLES ║
-- ╠══════════════════════════════════════════════════════════╣
-- ║ These 4 tables each have a single RLS policy of the form:║
-- ║                                                          ║
-- ║   policy_name:       anon_all_{table}                    ║
-- ║   command:           ALL                                 ║
-- ║   roles:             {public}                            ║
-- ║   using_clause:      true                                ║
-- ║   with_check_clause: true                                ║
-- ║                                                          ║
-- ║ Meaning: anyone holding the Supabase anon key (a public  ║
-- ║ key by design) can SELECT / INSERT / UPDATE / DELETE     ║
-- ║ every row in customers, prescriptions, sales, and        ║
-- ║ work_orders across every tenant, with no filtering.      ║
-- ║                                                          ║
-- ║ Compounding factor: these are ALSO the only 4 tables in  ║
-- ║ the live DB that lack a tenant_id column (confirmed via  ║
-- ║ db-audit/02-columns.md against db-audit/01-tables.md).   ║
-- ║ The missing tenant_id and the anon_all_* policies are    ║
-- ║ the same problem wearing two masks — these tables were   ║
-- ║ created before multi-tenancy was enforced and never      ║
-- ║ retrofitted.                                             ║
-- ║                                                          ║
-- ║ Tables affected: customers, prescriptions, sales,        ║
-- ║                  work_orders                             ║
-- ║ Policy text:     db-audit/04-policies.md (rows for       ║
-- ║                  customers, prescriptions, sales,        ║
-- ║                  work_orders)                            ║
-- ║ Remediation:     tracked in MASTER_ROADMAP.md under      ║
-- ║                  Module 3 Phase B preamble checklist.    ║
-- ║                                                          ║
-- ║ DO NOT "FIX" THIS IN THIS FILE. Phase 3A is read-only    ║
-- ║ on the DB. This block DOCUMENTS reality.                 ║
-- ╚══════════════════════════════════════════════════════════╝


-- ============================================================
-- VIEWS (24 total)
-- Full definitions: db-audit/03-views.md (authoritative).
-- This section is a summary index + the ONE golden-reference view.
-- ============================================================

--   Admin views (8) — used by ERP Studio / Platform Admin UIs:
--     v_admin_campaign_templates  — active campaign templates (is_deleted=false)
--     v_admin_campaigns           — active campaigns + page_count subquery
--     v_admin_component_presets   — component presets (is_deleted=false)
--     v_admin_components          — all storefront_components
--     v_admin_leads               — all cms_leads, newest first
--     v_admin_media               — media_library (is_deleted=false)
--     v_admin_pages               — storefront_pages including drafts
--     v_admin_product_picker      — inventory + brand + images for admin picker
--     v_admin_reviews             — all storefront_reviews, by sort_order
--
--   Storefront read views (13) — anon-facing, all Views-only per Iron Rule #13:
--     v_public_tenant             — tenant + storefront_config resolution
--     v_storefront_blog_posts     — published blog posts
--     v_storefront_brand_page     — brand landing pages (brand_page_enabled=true)
--     v_storefront_brands         — brand index + product_count filter
--     v_storefront_categories     — product_type aggregates
--     v_storefront_components     — active components only
--     v_storefront_config         — per-tenant storefront settings
--     v_storefront_media          — media_library (is_deleted=false, public shape)
--     v_storefront_pages          — published pages only
--     v_storefront_products       — GOLDEN REFERENCE — see verbatim below
--     v_storefront_reviews        — visible reviews only
--     v_ai_content                — active ai_content rows
--     v_content_translations      — approved + draft translations
--
--   Other (3):
--     v_tenant_i18n_overrides     — passthrough of tenant_i18n_overrides
--     v_translation_dashboard     — pivoted storefront_pages he/en/ru status
--     (+ the admin / storefront views above total 24 with these 3)

-- ------------------------------------------------------------
-- GOLDEN REFERENCE — v_storefront_products
-- DO NOT MODIFY WITHOUT A REGRESSION TEST.
-- This view's `images` subquery is the single source of truth for
-- storefront product image URLs, and its website_sync filter is the
-- single source of truth for which inventory rows are visible to the
-- storefront. Per CLAUDE.md §4 Iron Rule #13 and §11 regression rules
-- and per opticup-storefront/CLAUDE.md §5 View Modification Protocol.
-- Verbatim from db-audit/03-views.md row `v_storefront_products`.
-- ------------------------------------------------------------
-- Rewritten 2026-04-27 by STOREFRONT_SYNC_HIERARCHY_FIX_2026_04_27
-- Hierarchy (highest priority first):
--   1. inventory.display_mode_override (Studio Products override) — wins
--   2. brands.brand_page_visibility (Studio Brands page-show toggle) — gates inclusion
--   3. inventory.website_sync (per-product) — primary visibility driver
--   (no fallback to brands.display_mode — now a seed field only)
CREATE OR REPLACE VIEW v_storefront_products AS
 SELECT i.id,
    i.tenant_id,
    i.barcode,
    b.name AS brand_name,
    b.id AS brand_id,
    b.brand_type,
    i.model,
    i.color,
    i.size,
    i.quantity,
    i.product_type,
    i.sell_price,
    i.sell_discount,
    i.website_sync,
    CASE
      WHEN i.display_mode_override IS NOT NULL THEN i.display_mode_override
      WHEN COALESCE(i.website_sync, 'full'::text) = 'display' THEN 'catalog'::text
      ELSE 'store_all'::text
    END AS display_mode,
    i.display_mode_override,
    COALESCE(( SELECT json_agg(('/api/image/'::text || img.storage_path) ORDER BY img.sort_order, img.created_at) AS json_agg
           FROM inventory_images img
          WHERE (img.inventory_id = i.id)), '[]'::json) AS images,
    lower(((((((COALESCE(b.name, ''::text) || ' '::text) || COALESCE(i.model, ''::text)) || ' '::text) || COALESCE(i.color, ''::text)) || ' '::text) || COALESCE(i.barcode, ''::text))) AS search_text,
    CASE
      WHEN i.display_mode_override = 'catalog' THEN 'catalog'::text
      WHEN COALESCE(i.website_sync, 'full'::text) = 'display' THEN 'catalog'::text
      ELSE 'shop'::text
    END AS resolved_mode,
    ( SELECT ai_content.content
           FROM ai_content
          WHERE ((ai_content.entity_type = 'product'::text) AND (ai_content.entity_id = i.id) AND (ai_content.content_type = 'description'::text) AND (ai_content.language = 'he'::text) AND (ai_content.is_deleted = false))
          ORDER BY ai_content.version DESC
         LIMIT 1) AS ai_description,
    ( SELECT ai_content.content
           FROM ai_content
          WHERE ((ai_content.entity_type = 'product'::text) AND (ai_content.entity_id = i.id) AND (ai_content.content_type = 'seo_title'::text) AND (ai_content.language = 'he'::text) AND (ai_content.is_deleted = false))
          ORDER BY ai_content.version DESC
         LIMIT 1) AS ai_seo_title,
    ( SELECT ai_content.content
           FROM ai_content
          WHERE ((ai_content.entity_type = 'product'::text) AND (ai_content.entity_id = i.id) AND (ai_content.content_type = 'seo_description'::text) AND (ai_content.language = 'he'::text) AND (ai_content.is_deleted = false))
          ORDER BY ai_content.version DESC
         LIMIT 1) AS ai_seo_description
   FROM (inventory i
     JOIN brands b ON ((i.brand_id = b.id)))
  WHERE ((i.is_deleted = false) AND (b.active = true) AND (b.exclude_website IS NOT TRUE) AND (COALESCE(i.website_sync, 'full'::text) <> 'none'::text) AND ((b.brand_page_visibility IS NULL) OR (b.brand_page_visibility <> 'hidden'::text)) AND ((i.display_mode_override IS NULL) OR (i.display_mode_override <> 'hidden'::text)) AND (EXISTS ( SELECT 1
           FROM inventory_images img
          WHERE (img.inventory_id = i.id))) AND (i.barcode IS NOT NULL));

-- v_storefront_brands also rewritten 2026-04-27 — display_mode now derived from per-product mix
CREATE OR REPLACE VIEW v_storefront_brands AS
 SELECT b.id AS brand_id,
    b.tenant_id,
    b.name AS brand_name,
    b.slug,
    b.hero_image,
    b.video_url,
    b.logo_url,
    b.brand_description,
    b.brand_description_short,
    ( SELECT jsonb_agg(ml.storage_path ORDER BY arr.idx) AS jsonb_agg
           FROM jsonb_array_elements_text(b.brand_gallery) WITH ORDINALITY arr(val, idx)
             LEFT JOIN media_library ml ON (((ml.id = (arr.val)::uuid) AND (ml.is_deleted = false)))
          WHERE (ml.storage_path IS NOT NULL)) AS brand_gallery,
    b.seo_title,
    b.seo_description,
    b.brand_page_enabled,
    CASE
      WHEN EXISTS (SELECT 1 FROM inventory i
                    WHERE (i.brand_id = b.id) AND (i.tenant_id = b.tenant_id)
                      AND (i.is_deleted = false) AND (i.website_sync = 'full'::text))
        THEN 'store_all'::text
      WHEN EXISTS (SELECT 1 FROM inventory i
                    WHERE (i.brand_id = b.id) AND (i.tenant_id = b.tenant_id)
                      AND (i.is_deleted = false) AND (i.website_sync = 'display'::text))
        THEN 'catalog'::text
      ELSE 'store_all'::text
    END AS display_mode,
    b.brand_page_visibility,
    b.show_brand_products,
    ( SELECT count(DISTINCT i.id) AS count
        FROM inventory i
       WHERE (i.brand_id = b.id) AND (i.tenant_id = b.tenant_id)
         AND (i.is_deleted = false)
         AND (COALESCE(i.website_sync, 'full'::text) <> 'none'::text)
         AND ((i.display_mode_override IS NULL) OR (i.display_mode_override <> 'hidden'::text))
         AND (EXISTS (SELECT 1 FROM inventory_images img WHERE (img.inventory_id = i.id)))) AS product_count
   FROM brands b
  WHERE ((b.is_deleted = false) AND (b.active = true) AND (b.exclude_website IS NOT TRUE)
         AND ((b.brand_page_visibility IS NULL) OR (b.brand_page_visibility <> 'hidden'::text))
         AND EXISTS (SELECT 1 FROM inventory i
                      WHERE (i.brand_id = b.id) AND (i.tenant_id = b.tenant_id)
                        AND (i.is_deleted = false)
                        AND (COALESCE(i.website_sync, 'full'::text) <> 'none'::text)));


-- ============================================================
-- RLS POLICIES (162 total across all 84 tables)
-- Full policy text: db-audit/04-policies.md (authoritative).
-- ============================================================
--
-- Every table in db-audit/01-tables.md has rls_enabled = true (none forced).
-- The standard shape across ~75 tables is:
--
--     CREATE POLICY tenant_isolation ON <table>
--       FOR ALL TO public
--       USING (tenant_id = (((current_setting('request.jwt.claims', true))::json
--                             ->> 'tenant_id'))::uuid);
--
--     CREATE POLICY service_bypass ON <table>
--       FOR ALL TO service_role
--       USING (true);
--
-- Exceptions and outliers are flagged as SECURITY-FINDING blocks below.
-- Policy-count exceptions (tables with more or fewer than the standard
-- two policies) are listed in db-audit/04-policies.md and include:
-- campaign_templates, campaigns, cms_leads, content_performance,
-- content_translations, content_versions, media_library, plans,
-- platform_admins, platform_audit_log, storefront_block_templates,
-- storefront_component_presets, storefront_components, storefront_config,
-- storefront_pages, storefront_reviews, storefront_templates, tenant_config,
-- tenant_provisioning_log, tenants, translation_memory.

-- NOTE ON supplier_balance_adjustments.service_bypass:
-- `service_bypass` is the canonical policy name for the service_role bypass
-- half of the canonical two-policy RLS pattern. Reference implementation:
-- the policy pair on `pending_sales`. See CLAUDE.md Iron Rule #15
-- Canonical RLS Pattern. This was initially flagged as SECURITY-FINDING #2
-- ("misnamed bypass") by Phase 3A; Daniel's verification on 2026-04-11
-- confirmed it is a false positive — the name is correct and matches the
-- project convention. The original FINDING block was removed by Phase 3D.
-- Policy text: db-audit/04-policies.md line 148.

-- ╔══════════════════════════════════════════════════════════╗
-- ║ SECURITY-FINDING #3 — auth.uid() USED AS tenant_id ON    ║
-- ║ THREE TABLES (Pattern 3 bug)                             ║
-- ╠══════════════════════════════════════════════════════════╣
-- ║ The following three tables use `auth.uid()` as the       ║
-- ║ tenant-isolation check, instead of a JWT claim or        ║
-- ║ session variable:                                        ║
-- ║                                                          ║
-- ║  1. brand_content_log                                    ║
-- ║     policy: "Tenant brand content log" / ALL / {public}  ║
-- ║     using:  ((tenant_id = auth.uid()) OR                 ║
-- ║              EXISTS (SELECT 1 FROM tenants               ║
-- ║               WHERE tenants.id = brand_content_log       ║
-- ║                                     .tenant_id))         ║
-- ║                                                          ║
-- ║  2. storefront_component_presets                         ║
-- ║     policy: "Tenant or global presets visible" / SELECT  ║
-- ║     using:  ((tenant_id IS NULL) OR                      ║
-- ║              (tenant_id = auth.uid()))                   ║
-- ║     (also: "Tenant can manage own presets" / ALL /       ║
-- ║      using (tenant_id IS NOT NULL) — equally permissive) ║
-- ║                                                          ║
-- ║  3. storefront_page_tags                                 ║
-- ║     policy: "Tenant page tags" / ALL / {public}          ║
-- ║     using:  ((tenant_id = auth.uid()) OR                 ║
-- ║              EXISTS (SELECT 1 FROM tenants               ║
-- ║               WHERE tenants.id = storefront_page_tags    ║
-- ║                                     .tenant_id))         ║
-- ║                                                          ║
-- ║ WHY THIS IS A BUG: auth.uid() returns the signed-in      ║
-- ║ Supabase user UUID, not the Optic Up tenant UUID. The    ║
-- ║ check `tenant_id = auth.uid()` is therefore comparing    ║
-- ║ a tenant id against a user id — they are distinct        ║
-- ║ namespaces and will almost never match. The secondary    ║
-- ║ EXISTS-over-tenants clause in #1 and #3 additionally     ║
-- ║ matches ANY row whose tenant_id points at any existing   ║
-- ║ tenant, i.e. it resolves to "true" in every real row,    ║
-- ║ which nullifies isolation entirely.                      ║
-- ║                                                          ║
-- ║ Why this has not caused an incident yet: writes to       ║
-- ║ these three tables currently go through service_role     ║
-- ║ code paths only (Storefront Studio admin + brand content ║
-- ║ generator), and service_role bypasses RLS. The broken    ║
-- ║ isolation is latent until a public-facing write path     ║
-- ║ is added to any of these tables.                         ║
-- ║                                                          ║
-- ║ Policy text: db-audit/04-policies.md lines 22-24         ║
-- ║              (brand_content_log),                        ║
-- ║              lines 125-126 (storefront_component_presets)║
-- ║              lines 136-138 (storefront_page_tags)        ║
-- ║ Remediation: tracked in MASTER_ROADMAP.md under          ║
-- ║              Module 3 Phase B preamble checklist.        ║
-- ╚══════════════════════════════════════════════════════════╝

-- MINOR OUTLIER (not a security finding):
--   public.tenant_config.tenant_config_tenant_read uses `::jsonb` cast,
--   while every other JWT-based policy uses `::json`. Both work — pg
--   casts text to either. Flagged here only so a future migration sweep
--   picks it up. See db-audit/04-policies.md line 169.


-- ============================================================
-- FUNCTIONS (72 total in public schema)
-- Full list with signatures: db-audit/05-functions.md.
-- Split into two subsections: project code vs extension noise.
-- Function BODIES are not exposed by information_schema; verifying
-- implementation details (FOR UPDATE, SECURITY DEFINER logic, etc.)
-- is SEPARATE WORK, not performed by this audit.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Project functions (41) — plpgsql / sql, Optic Up code
-- ------------------------------------------------------------

--   Tenant lifecycle (Module 2 — Platform Admin):
--     activate_tenant(p_tenant_id, p_admin_id) -> void
--     create_tenant(p_name, p_slug, p_owner_name, p_owner_email,
--                   p_owner_phone, p_plan_id, p_admin_pin, p_admin_name,
--                   p_created_by) -> uuid
--     delete_tenant(p_tenant_id, p_deleted_by) -> void
--     suspend_tenant(p_tenant_id, p_reason, p_admin_id) -> void
--     update_tenant(p_tenant_id, p_updates, p_admin_id) -> void
--     get_all_tenants_overview() -> jsonb
--     get_tenant_activity_log(...) -> jsonb
--     get_tenant_employees(p_tenant_id) -> jsonb
--     get_tenant_stats(p_tenant_id) -> jsonb
--     validate_slug(p_slug) -> jsonb
--
--   Plan / feature gates:
--     check_plan_limit(p_tenant_id, p_resource) -> jsonb
--     is_feature_enabled(p_tenant_id, p_feature) -> boolean
--     is_platform_super_admin() -> boolean
--
--   Inventory (atomic writes — Iron Rule #1 atomicity):
--     decrement_inventory(inv_id, delta) -> void
--     increment_inventory(inv_id, delta) -> void
--     set_inventory_qty(inv_id, new_qty) -> void
--     apply_stock_count_delta(p_inventory_id, p_counted_qty, p_tenant_id,
--                             p_user_id, p_count_id) -> json
--     get_low_stock_brands() -> TABLE(...)
--
--   Sequential number generators (Iron Rule #13):
--     next_box_number(p_tenant_id uuid) -> text
--     next_internal_doc_number(p_tenant_id uuid, p_prefix text) -> text
--     next_po_number(p_tenant_id uuid, p_supplier_number text) -> text
--     next_return_number(p_tenant_id uuid, p_supplier_number text) -> text
--     NOTE: information_schema does not expose function bodies, so this
--     audit does NOT confirm FOR UPDATE locking. Verifying Iron Rule #13
--     compliance is a separate task tracked outside Phase 3A.
--
--   Shipments / debt / payments:
--     increment_shipment_counters(p_shipment_id, p_items_delta,
--                                 p_value_delta) -> void
--     increment_paid_amount(p_doc_id, p_delta) -> void
--     increment_prepaid_used(p_deal_id, p_delta) -> void
--     get_po_aggregates(p_tenant_id) -> TABLE(po_id, item_count, total_value)
--
--   Auth:
--     reset_employee_pin(p_tenant_id, p_employee_id, p_new_pin,
--                        p_must_change, p_admin_id) -> void
--
--   Alerts:
--     generate_daily_alerts(p_tenant_id) -> json
--
--   Storefront leads / content / translations (Module 3):
--     submit_storefront_lead(p_tenant_id, p_inventory_id, p_contact_type,
--                            p_contact_value) -> uuid
--     create_translated_page(p_tenant_id, p_source_page_id, p_target_lang,
--                            p_translated_blocks, p_title, p_slug,
--                            p_meta_title, p_meta_description) -> uuid
--     mark_translations_stale(p_page_id, p_changed_blocks) -> integer
--     get_translation_context(p_tenant_id, p_target_lang, p_limit) -> jsonb
--     save_translation_memory_batch(p_entries jsonb) -> void            -- overload #1
--     save_translation_memory_batch(p_tenant_id, p_entries) -> integer  -- overload #2
--     promote_to_platform(p_memory_ids uuid[]) -> integer
--
--   OCR templates:
--     update_ocr_template_stats(p_tenant_id, p_supplier_id, p_doc_type_code,
--                               p_was_corrected, p_new_hints) -> json     -- overload #1
--     update_ocr_template_stats(p_tenant_id, p_supplier_id, p_doc_type_code,
--                               p_was_corrected, p_new_hints,
--                               p_fields_suggested, p_fields_accepted) -> json   -- overload #2
--
--   Triggers (trigger functions, no direct call):
--     save_previous_blocks() -> trigger
--     update_storefront_components_updated_at() -> trigger
--     update_storefront_pages_updated_at() -> trigger
--     update_storefront_reviews_updated_at() -> trigger
--     update_updated_at() -> trigger

-- ------------------------------------------------------------
-- 2. Extension functions (31) — pg_trgm, NOT Optic Up code
-- ------------------------------------------------------------
-- Installed automatically by `CREATE EXTENSION pg_trgm`. Language `c`,
-- IMMUTABLE volatility, not security definer. Managed by the extension.
-- These appear in db-audit/05-functions.md only because the audit query
-- scans all functions in the public schema. Do NOT document them here.
-- Full list: db-audit/05-functions.md rows where language = 'c'.
--
-- Family summary:
--   GiST operator-class support:
--     gtrgm_in, gtrgm_out, gtrgm_compress, gtrgm_decompress,
--     gtrgm_consistent, gtrgm_distance, gtrgm_options,
--     gtrgm_penalty, gtrgm_picksplit, gtrgm_same, gtrgm_union
--   GIN operator-class support:
--     gin_extract_query_trgm, gin_extract_value_trgm,
--     gin_trgm_consistent, gin_trgm_triconsistent
--   Similarity scalars & operators:
--     similarity, similarity_dist, similarity_op, show_trgm,
--     word_similarity, word_similarity_commutator_op,
--     word_similarity_dist_commutator_op, word_similarity_dist_op,
--     word_similarity_op, strict_word_similarity,
--     strict_word_similarity_commutator_op,
--     strict_word_similarity_dist_commutator_op,
--     strict_word_similarity_dist_op, strict_word_similarity_op,
--     set_limit, show_limit


-- ============================================================
-- SEQUENCES
-- ============================================================
-- No Postgres sequences exist in the public schema (confirmed 2026-04-11
-- via pg_sequences query — see db-audit/06-sequences.md). This is a
-- deliberate architectural choice, not a gap:
--
--   * All primary keys use UUIDs (gen_random_uuid / uuid_generate_v4).
--   * All human-readable sequential numbers (PO, return, box, internal
--     doc) are generated by SECURITY DEFINER RPCs. See the
--     `next_*_number` entries in the FUNCTIONS section above and the
--     signatures in db-audit/05-functions.md.
--   * Iron Rule #13 requires that these RPCs use `FOR UPDATE` locking
--     internally. Verifying that the actual function bodies comply is
--     SEPARATE WORK and is NOT confirmed by this audit — information_schema
--     does not expose function bodies.
--
-- If a future migration ever adds a CREATE SEQUENCE to public, update
-- this section and file a follow-up to reassess the RPC-only pattern.

-- ============================================================
-- PUBLIC DATA LAYER (added 2026-05-15 by STOREFRONT_PUBLIC_DATA_LAYER_2026_05_15)
-- ============================================================
-- A structurally-separate set of mirror tables sitting between the private
-- source-of-truth tables and every public consumer (storefront, future
-- Standard-tier shared site, M11 Supplier Portal, customer portal, API).
-- After this SPEC closed, anon SELECT is MECHANICALLY impossible against
-- the 6 private base tables (inventory, brands, media_library,
-- tenant_branches, storefront_config, inventory_images) and against
-- v_crm_lead_first_touch.
--
-- Canonical reference: docs/PUBLIC_DATA_LAYER.md.
-- Retrospective + DDL provenance:
--   modules/Module 1.5 - Shared Components/docs/specs/STOREFRONT_PUBLIC_DATA_LAYER_2026_05_15/
--     SPEC.md + EXECUTION_REPORT.md + FINDINGS.md + REVIEW.md +
--     TEST_REPORT.md + FOREMAN_REVIEW.md + VIEW_REWRITE_SUMMARY.md +
--     REVOKE_SUMMARY.md + VERIFICATION_REPORT.md.
-- Live DDL: Supabase's supabase_migrations.schema_migrations table (records
-- 6 create_*_public_layer + fix_mirror_column_precision +
-- add_has_sellable_inventory_to_brands_public +
-- rewrite_8_storefront_views_source_from_public_layer_v2 +
-- revoke_anon_select_from_private_bases_and_crm_view).
--
-- 6 mirror tables (all tenant_id NOT NULL REFERENCES tenants(id) + RLS):
--   branches_public            — mirrors tenant_branches (status='published' AND is_deleted=false)
--   storefront_config_public   — mirrors storefront_config (enabled=true)
--   media_public               — mirrors media_library (is_deleted=false)
--   brands_public              — mirrors brands (is_deleted=false AND active=true AND exclude_website IS NOT TRUE)
--                                + cached column has_sellable_inventory (refreshed by satellite trigger)
--   inventory_images_public    — mirrors inventory_images (no filter)
--   inventory_public           — mirrors inventory (8-condition filter)
--                                + cached AI columns (ai_description, ai_seo_title, ai_seo_description from ai_content)
--                                + cached image_paths text[] from inventory_images
--
-- 18 RLS policies (3 per mirror, all Pattern 1 JWT-claim per CONVENTIONS):
--   per mirror: service_bypass + tenant_isolation + <table>_anon_public_read
--
-- 6 GRANTs: GRANT SELECT ON <mirror>_public TO anon (and authenticated).
--
-- 9 trigger functions (SECURITY DEFINER + SET search_path = public, pg_temp):
--   sync_branches_public_trg, sync_storefront_config_public_trg,
--   sync_media_public_trg, sync_brands_public_trg,
--   sync_inventory_images_public_trg, sync_inventory_public_trg,
--   sync_ai_content_to_inventory_public_trg (satellite),
--   sync_inventory_images_to_inventory_public_trg (satellite),
--   sync_inventory_to_brands_has_sellable_trg (satellite, refreshes
--     brands_public.has_sellable_inventory when inventory changes).
--
-- 9 triggers on private bases (AFTER INSERT OR UPDATE OR DELETE):
--   tr_sync_branches_public, tr_sync_storefront_config_public,
--   tr_sync_media_public, tr_sync_brands_public,
--   tr_sync_inventory_images_public, tr_sync_inventory_public,
--   tr_sync_ai_content_to_inventory_public (on ai_content),
--   tr_sync_inventory_images_to_inventory_public (2nd trigger on
--     inventory_images alongside tr_sync_inventory_images_public),
--   tr_sync_inventory_to_brands_has_sellable (2nd trigger on inventory
--     alongside tr_sync_inventory_public).
--
-- 8 v_storefront_* views REWRITTEN to read from this layer + flipped
--   security_invoker=on (closed 8 F-CRIT-2 advisor findings):
--   v_storefront_branches    → branches_public
--   v_storefront_config      → storefront_config_public
--   v_storefront_media       → media_public
--   v_public_tenant          → tenants JOIN storefront_config_public
--   v_storefront_products    → inventory_public JOIN brands_public
--   v_storefront_brands      → brands_public (chained inventory_public,
--                               media_public; filters has_sellable_inventory)
--   v_storefront_brand_page  → brands_public (chained v_storefront_products,
--                               media_public)
--   v_storefront_categories  → chained on v_storefront_products
--
-- 7 REVOKEs anon SELECT (mechanical separation):
--   inventory, brands, media_library, tenant_branches, storefront_config,
--   inventory_images, v_crm_lead_first_touch.
--
-- NOT in this layer (intentional):
--   tenants — kept anon-readable via anon_read_tenants USING(true). Storefront
--     needs slug resolution. If tightening is needed in the future, build a
--     tenants_public follow-up SPEC.
--   ai_content — kept anon-readable via ai_content_public_read_published
--     USING(status='published'). Currently 0 rows match. Rewritten
--     v_storefront_products reads AI from cached columns in inventory_public,
--     NOT directly from ai_content.

-- ═══════════════════════════════════════════════════════════════
-- Module 5 — Customers (sealed Phase A+B 2026-05-22)
-- Detailed DDL: modules/Module 5 - Customers/docs/db-schema.sql
-- ═══════════════════════════════════════════════════════════════

-- Extensions on existing tables (additive):
--   ALTER TABLE tenants       ADD COLUMN tenant_code text NOT NULL UNIQUE
--      Backfilled: prizma='01', demo='02'.
--   ALTER TABLE tenant_location ADD COLUMN deactivated_at timestamptz NULL
--   ALTER TABLE customers     RENAME branch_id → home_branch_id;
--      + 26 new columns (first_name, last_name, customer_number, lifecycle_stage,
--        household_id, health_fund_id, language_code, gender, profession,
--        dominant_eye, 4 consent booleans, source, utm_*×6, first_interaction_at,
--        consent_form_signed_at, is_deleted, deleted_at, updated_by).
--      Total post-ALTER: 42 columns. Canonical 2-policy RLS preserved.

-- New enums (4): customer_lifecycle_stage, household_status, customer_note_type,
--   customer_document_category.

-- New tables (8):
--   households, health_funds, tenant_languages, customer_notes, customer_documents,
--   tenant_settings, tenant_number_counters, (and customers extended above).
-- All RLS canonical 2-policy. All FK columns indexed. Tenant-scoped UNIQUE on
-- (customer_number, tenant_id) WHERE not NULL; (phone, tenant_id) WHERE NOT NULL
-- AND is_deleted=false; (id_number, tenant_id) WHERE NOT NULL AND is_deleted=false;
-- (code, tenant_id) on health_funds; (language_code, tenant_id) on tenant_languages.

-- Seed: tenant_languages 8 rows (he default, ru, en active, es inactive — per tenant);
--   health_funds 10 rows (Leumit, Maccabi, Clalit, Clalit Platinum, Meuhedet — per tenant).

-- Views (7 customer-data, all security_invoker=on):
--   v_customer_for_exam, _for_order, _for_payment, _full, _for_messaging,
--   _for_loyalty, _for_appointment.

-- RPCs (8 functions, all SECURITY DEFINER + search_path SET + Block A header):
--   create_customer, merge_customers, assign_to_household,
--   delete_last_unused_customer (Iron Rule 32), update_customer_display_preferences,
--   allocate_tenant_number (shared infra),
--   compute_lifecycle_stage_on_order (deferred trigger — M7 wires),
--   compute_lifecycle_dormant_sweep (deferred stub — M7 adds body).
-- REVOKE EXECUTE FROM anon, PUBLIC + GRANT EXECUTE TO authenticated, service_role.

-- ═══════════════════════════════════════════════════════════════
-- Module 6 — Prescriptions / Eye Exams (sealed Phase A+B 2026-05-22)
-- Detailed DDL: modules/Module 6 - Prescriptions/docs/db-schema.sql
-- ═══════════════════════════════════════════════════════════════

-- New enums (19):
--   exam_status, exam_outcome, exam_type, prescription_status, prescription_source,
--   prescription_exam_reason, prescription_treatment, prescription_refraction_method,
--   glasses_lens_type, glasses_lens_material, prism_base, eye_side,
--   cl_lens_type, cl_replacement_period, cl_wear_schedule, cl_material, cl_tint,
--   recall_axis_kind, prescription_kind.

-- New tables (8):
--   eye_exams, prescriptions_glasses, prescription_glasses_eyes (Pattern 11),
--   prescriptions_contacts, prescription_contacts_eyes (Pattern 11),
--   prescription_types (config P19, capability flags), lens_manufacturers (config P19),
--   prescription_recall_axes.
-- All RLS canonical 2-policy. Tenant-scoped UNIQUE: (prescription_number, tenant_id)
-- WHERE not NULL on both prescription tables; (code, tenant_id) on prescription_types
-- and lens_manufacturers; (prescription_id, eye) on both eye tables.
-- ON DELETE CASCADE from parent prescription to child eyes.

-- Seed: prescription_types 16 rows (8 default types per tenant: for_distance,
--   for_reading, for_computer, progressive, bifocal, multifocal_cl, for_sunglasses,
--   health_fund); lens_manufacturers 10 rows (acuvue, air_optix, proclear, biofinity,
--   dailies — per tenant).

-- Views (9 — all security_invoker=on):
--   v_exam_for_customer, v_exam_for_doctor,
--   v_prescription_glasses_for_order, v_prescription_contacts_for_order,
--   v_recall_due (window-fn 1-row-per-prescription),
--   v_prescription_history_for_customer (UNION glasses+contacts),
--   v_customer_prescriptions_summary (cross-contract — M5 customer card consumes),
--   v_prescription_full_for_editor, v_prescriptions_list_for_customer (UNION).

-- RPCs (7, all SECURITY DEFINER + search_path + Block A):
--   create_exam, create_prescription_draft (M5↔M6 entry-point),
--   commit_prescription (atomic; calls allocate_tenant_number for prescription_number;
--     fires compute_recall_due_dates), cancel_draft_prescription (Iron Rule 32 — no
--     counter touch on draft cancel), supersede_prescription, compute_recall_due_dates
--     (multi-axis: 4 for glasses, 5 for contacts including fit_check),
--     clone_prescription.
-- REVOKE EXECUTE FROM anon, PUBLIC + GRANT EXECUTE TO authenticated, service_role.

-- Re-uses M5 infrastructure: tenant_number_counters + allocate_tenant_number(p_tenant_id,
-- 'prescription'). Iron Rule 11 + 32 both preserved across modules.

-- ═══════════════════════════════════════════════════════════════
-- End of GLOBAL_SCHEMA.sql
-- ═══════════════════════════════════════════════════════════════
