-- ═══════════════════════════════════════════════════════════════
-- GLOBAL SCHEMA — Optic Up
-- Reconciled from live DB: 2026-04-11 (Phase 3A Part 2)
-- Sources: modules/Module 3.1 - Project Reconstruction/db-audit/
--            01-tables.md     — 84 base tables
--            02-columns.md    — column-level detail (base tables + view columns)
--            03-views.md      — 24 views with full definitions
--            04-policies.md   — 162 RLS policies
--            05-functions.md  — 72 functions (41 project + 31 extension)
--            06-sequences.md  — 0 sequences (by design — UUID + RPC)
--
-- AUTHORITATIVE for table / view / policy / function declarations.
-- Per-module db-schema.sql files reference THIS file, not the reverse.
--
-- This file is a MAP. Column types, defaults, CHECK constraints, and full
-- policy / function / view bodies live in the db-audit/*.md source files.
-- Do not duplicate that content here — keep this file scannable.
--
-- Prior version: 2026-03-24 snapshot, stale at table level (missing 24 tables,
-- missing all 24 views, missing the AI content / translation / storefront CMS
-- surface). Backed up under
-- modules/Module 3.1 - Project Reconstruction/backups/M3.1-3A_2026-04-11/.
-- ═══════════════════════════════════════════════════════════════


-- ============================================================
-- CONVENTIONS — read this before adding or changing anything
-- ============================================================
--
-- TENANT ISOLATION — three RLS idioms exist in the live DB today:
--
--   Pattern 1 — JWT claim                   (STANDARD — ~140 policies)
--     (tenant_id = (((current_setting('request.jwt.claims', true))::json
--                    ->> 'tenant_id'))::uuid)
--     Used by every table in Modules 1, 1.5, 2, and most of Module 3.
--     All NEW tables MUST use this pattern.
--
--   Pattern 2 — Postgres session variable   (LEGACY — migrate to Pattern 1)
--     (tenant_id = (current_setting('app.tenant_id', true))::uuid)
--     Currently used by: media_library, campaigns, campaign_templates,
--                        supplier_balance_adjustments.
--     Functional, but inconsistent with the rest of the codebase.
--     Migration tracked in MASTER_ROADMAP.md (Module 3 Phase B preamble).
--
--   Pattern 3 — auth.uid() as tenant_id     (BUG — do not copy)
--     Currently used by: brand_content_log, storefront_component_presets,
--                        storefront_page_tags.
--     auth.uid() returns the authenticated USER uuid, not the tenant uuid,
--     so every signed-in user becomes their own "tenant" on these tables.
--     Works today only because service_role bypasses RLS on every write.
--     See SECURITY-FINDING block under RLS POLICIES below.
--
-- EVERY NEW TABLE MUST:
--   - have tenant_id UUID NOT NULL REFERENCES tenants(id)    (Iron Rule #14)
--   - have ENABLE ROW LEVEL SECURITY                          (Iron Rule #15)
--   - use Pattern 1 for its tenant_isolation policy
--   - carry tenant_id in every UNIQUE constraint               (Iron Rule #18)
--
-- PRIMARY KEYS — UUID everywhere (gen_random_uuid() or uuid_generate_v4()).
-- Sequential numbers (PO / return / box / internal doc) are generated by
-- SECURITY DEFINER RPCs, not by Postgres sequences (Iron Rule #13).
-- See FUNCTIONS and SEQUENCES sections below.
--
-- EXTENSIONS REQUIRED — uuid-ossp, pg_trgm.


-- ============================================================
-- TABLES (84 total, grouped by owning module)
-- Full column lists live in db-audit/02-columns.md.
-- Every table has rls_enabled=true (see db-audit/01-tables.md).
-- ============================================================

-- ------------------------------------------------------------
-- Module 1 — Inventory Management / Core ERP (36 tables)
-- ------------------------------------------------------------
-- Catalog, purchasing, receiving, sales sync, debt tracking, OCR, shipments.

--   Brands & catalog:
--     brands, inventory, inventory_images, inventory_logs,
--     suppliers, supplier_documents, supplier_document_files,
--     supplier_ocr_templates, supplier_payments, supplier_returns,
--     supplier_return_items, supplier_balance_adjustments
--
--   Purchasing & receiving:
--     purchase_orders, purchase_order_items,
--     goods_receipts, goods_receipt_items,
--     document_types, document_links, payment_methods, payment_allocations,
--     currencies, prepaid_deals, prepaid_checks, expense_folders
--
--   Sync & stock counting:
--     sync_log, pending_sales, watcher_heartbeat,
--     stock_counts, stock_count_items
--
--   AI agent + OCR + alerts:
--     ai_agent_config, ocr_extractions, alerts, weekly_reports
--
--   Shipments (Phase 5.9):
--     courier_companies, shipments, shipment_items

-- ------------------------------------------------------------
-- Module 1.5 — Shared Components (14 tables)
-- ------------------------------------------------------------
-- Multi-tenant identity, auth, messaging, knowledge, activity audit.

--   Tenancy & employees:
--     tenants, employees
--
--   Auth & permissions:
--     roles, permissions, role_permissions, employee_roles, auth_sessions
--
--   Activity / audit:
--     activity_log
--
--   Messaging & knowledge:
--     conversations, conversation_participants, messages, message_reactions,
--     knowledge_base, notification_preferences

-- ------------------------------------------------------------
-- Module 2 — Platform Admin (5 tables)
-- ------------------------------------------------------------
-- Super-admin control plane over all tenants.

--   plans, platform_admins, platform_audit_log,
--   tenant_config, tenant_provisioning_log

-- ------------------------------------------------------------
-- Module 3 — Storefront (25 tables, in opticup-storefront repo at runtime)
-- ------------------------------------------------------------
-- CMS, campaigns, AI content, translations, media library, leads.
--
-- NOTE: the ERP repo owns these DEFINITIONS (this file + db-audit),
-- but the CONSUMER code lives in the sibling repo opticup-storefront.
-- Storefront consumers read via Views + RPC only (Iron Rules #13, #24).

--   Storefront CMS:
--     storefront_pages, storefront_config, storefront_leads,
--     storefront_block_templates, storefront_components,
--     storefront_component_presets, storefront_templates,
--     storefront_page_tags, storefront_reviews
--
--   CMS + campaigns + media:
--     cms_leads, media_library, blog_posts,
--     campaigns, campaign_templates, brand_content_log
--
--   AI content & SEO:
--     ai_content, ai_content_corrections, content_performance,
--     content_versions, seo_targets
--
--   Translation system:
--     content_translations, translation_memory, translation_glossary,
--     translation_corrections, tenant_i18n_overrides

-- ------------------------------------------------------------
-- Pre-multitenancy (4 tables) — SECURITY DEBT
-- ------------------------------------------------------------
-- customers, prescriptions, sales, work_orders
--
-- ╔══════════════════════════════════════════════════════════╗
-- ║ SECURITY-FINDING #1 — ANON READ/WRITE ON 4 LEGACY TABLES ║
-- ╠══════════════════════════════════════════════════════════╣
-- ║ These 4 tables each have a single RLS policy of the form:║
-- ║                                                          ║
-- ║   policy_name:       anon_all_{table}                    ║
-- ║   command:           ALL                                 ║
-- ║   roles:             {public}                            ║
-- ║   using_clause:      true                                ║
-- ║   with_check_clause: true                                ║
-- ║                                                          ║
-- ║ Meaning: anyone holding the Supabase anon key (a public  ║
-- ║ key by design) can SELECT / INSERT / UPDATE / DELETE     ║
-- ║ every row in customers, prescriptions, sales, and        ║
-- ║ work_orders across every tenant, with no filtering.      ║
-- ║                                                          ║
-- ║ Compounding factor: these are ALSO the only 4 tables in  ║
-- ║ the live DB that lack a tenant_id column (confirmed via  ║
-- ║ db-audit/02-columns.md against db-audit/01-tables.md).   ║
-- ║ The missing tenant_id and the anon_all_* policies are    ║
-- ║ the same problem wearing two masks — these tables were   ║
-- ║ created before multi-tenancy was enforced and never      ║
-- ║ retrofitted.                                             ║
-- ║                                                          ║
-- ║ Tables affected: customers, prescriptions, sales,        ║
-- ║                  work_orders                             ║
-- ║ Policy text:     db-audit/04-policies.md (rows for       ║
-- ║                  customers, prescriptions, sales,        ║
-- ║                  work_orders)                            ║
-- ║ Remediation:     tracked in MASTER_ROADMAP.md under      ║
-- ║                  Module 3 Phase B preamble checklist.    ║
-- ║                                                          ║
-- ║ DO NOT "FIX" THIS IN THIS FILE. Phase 3A is read-only    ║
-- ║ on the DB. This block DOCUMENTS reality.                 ║
-- ╚══════════════════════════════════════════════════════════╝


-- ============================================================
-- VIEWS (24 total)
-- Full definitions: db-audit/03-views.md (authoritative).
-- This section is a summary index + the ONE golden-reference view.
-- ============================================================

--   Admin views (8) — used by ERP Studio / Platform Admin UIs:
--     v_admin_campaign_templates  — active campaign templates (is_deleted=false)
--     v_admin_campaigns           — active campaigns + page_count subquery
--     v_admin_component_presets   — component presets (is_deleted=false)
--     v_admin_components          — all storefront_components
--     v_admin_leads               — all cms_leads, newest first
--     v_admin_media               — media_library (is_deleted=false)
--     v_admin_pages               — storefront_pages including drafts
--     v_admin_product_picker      — inventory + brand + images for admin picker
--     v_admin_reviews             — all storefront_reviews, by sort_order
--
--   Storefront read views (13) — anon-facing, all Views-only per Iron Rule #13:
--     v_public_tenant             — tenant + storefront_config resolution
--     v_storefront_blog_posts     — published blog posts
--     v_storefront_brand_page     — brand landing pages (brand_page_enabled=true)
--     v_storefront_brands         — brand index + product_count filter
--     v_storefront_categories     — product_type aggregates
--     v_storefront_components     — active components only
--     v_storefront_config         — per-tenant storefront settings
--     v_storefront_media          — media_library (is_deleted=false, public shape)
--     v_storefront_pages          — published pages only
--     v_storefront_products       — GOLDEN REFERENCE — see verbatim below
--     v_storefront_reviews        — visible reviews only
--     v_ai_content                — active ai_content rows
--     v_content_translations      — approved + draft translations
--
--   Other (3):
--     v_tenant_i18n_overrides     — passthrough of tenant_i18n_overrides
--     v_translation_dashboard     — pivoted storefront_pages he/en/ru status
--     (+ the admin / storefront views above total 24 with these 3)

-- ------------------------------------------------------------
-- GOLDEN REFERENCE — v_storefront_products
-- DO NOT MODIFY WITHOUT A REGRESSION TEST.
-- This view's `images` subquery is the single source of truth for
-- storefront product image URLs, and its website_sync filter is the
-- single source of truth for which inventory rows are visible to the
-- storefront. Per CLAUDE.md §4 Iron Rule #13 and §11 regression rules
-- and per opticup-storefront/CLAUDE.md §5 View Modification Protocol.
-- Verbatim from db-audit/03-views.md row `v_storefront_products`.
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW v_storefront_products AS
 SELECT i.id,
    i.tenant_id,
    i.barcode,
    b.name AS brand_name,
    b.id AS brand_id,
    b.brand_type,
    i.model,
    i.color,
    i.size,
    i.quantity,
    i.product_type,
    i.sell_price,
    i.sell_discount,
    i.website_sync,
    b.display_mode,
    i.display_mode_override,
    COALESCE(( SELECT json_agg(('/api/image/'::text || img.storage_path) ORDER BY img.sort_order, img.created_at) AS json_agg
           FROM inventory_images img
          WHERE (img.inventory_id = i.id)), '[]'::json) AS images,
    lower(((((((COALESCE(b.name, ''::text) || ' '::text) || COALESCE(i.model, ''::text)) || ' '::text) || COALESCE(i.color, ''::text)) || ' '::text) || COALESCE(i.barcode, ''::text))) AS search_text,
    COALESCE(i.storefront_mode_override, b.storefront_mode, 'catalog'::text) AS resolved_mode,
    ( SELECT ai_content.content
           FROM ai_content
          WHERE ((ai_content.entity_type = 'product'::text) AND (ai_content.entity_id = i.id) AND (ai_content.content_type = 'description'::text) AND (ai_content.language = 'he'::text) AND (ai_content.is_deleted = false))
          ORDER BY ai_content.version DESC
         LIMIT 1) AS ai_description,
    ( SELECT ai_content.content
           FROM ai_content
          WHERE ((ai_content.entity_type = 'product'::text) AND (ai_content.entity_id = i.id) AND (ai_content.content_type = 'seo_title'::text) AND (ai_content.language = 'he'::text) AND (ai_content.is_deleted = false))
          ORDER BY ai_content.version DESC
         LIMIT 1) AS ai_seo_title,
    ( SELECT ai_content.content
           FROM ai_content
          WHERE ((ai_content.entity_type = 'product'::text) AND (ai_content.entity_id = i.id) AND (ai_content.content_type = 'seo_description'::text) AND (ai_content.language = 'he'::text) AND (ai_content.is_deleted = false))
          ORDER BY ai_content.version DESC
         LIMIT 1) AS ai_seo_description
   FROM (inventory i
     JOIN brands b ON ((i.brand_id = b.id)))
  WHERE ((i.is_deleted = false) AND (b.active = true) AND (b.exclude_website IS NOT TRUE) AND (COALESCE(i.storefront_mode_override, b.storefront_mode, 'catalog'::text) <> 'hidden'::text) AND (i.website_sync = ANY (ARRAY['full'::text, 'display'::text])) AND ((i.website_sync = 'display'::text) OR ((i.website_sync = 'full'::text) AND (i.quantity > 0))) AND (EXISTS ( SELECT 1
           FROM inventory_images img
          WHERE (img.inventory_id = i.id))));


-- ============================================================
-- RLS POLICIES (162 total across all 84 tables)
-- Full policy text: db-audit/04-policies.md (authoritative).
-- ============================================================
--
-- Every table in db-audit/01-tables.md has rls_enabled = true (none forced).
-- The standard shape across ~75 tables is:
--
--     CREATE POLICY tenant_isolation ON <table>
--       FOR ALL TO public
--       USING (tenant_id = (((current_setting('request.jwt.claims', true))::json
--                             ->> 'tenant_id'))::uuid);
--
--     CREATE POLICY service_bypass ON <table>
--       FOR ALL TO service_role
--       USING (true);
--
-- Exceptions and outliers are flagged as SECURITY-FINDING blocks below.
-- Policy-count exceptions (tables with more or fewer than the standard
-- two policies) are listed in db-audit/04-policies.md and include:
-- campaign_templates, campaigns, cms_leads, content_performance,
-- content_translations, content_versions, media_library, plans,
-- platform_admins, platform_audit_log, storefront_block_templates,
-- storefront_component_presets, storefront_components, storefront_config,
-- storefront_pages, storefront_reviews, storefront_templates, tenant_config,
-- tenant_provisioning_log, tenants, translation_memory.

-- NOTE ON supplier_balance_adjustments.service_bypass:
-- `service_bypass` is the canonical policy name for the service_role bypass
-- half of the canonical two-policy RLS pattern. Reference implementation:
-- the policy pair on `pending_sales`. See CLAUDE.md Iron Rule #15
-- Canonical RLS Pattern. This was initially flagged as SECURITY-FINDING #2
-- ("misnamed bypass") by Phase 3A; Daniel's verification on 2026-04-11
-- confirmed it is a false positive — the name is correct and matches the
-- project convention. The original FINDING block was removed by Phase 3D.
-- Policy text: db-audit/04-policies.md line 148.

-- ╔══════════════════════════════════════════════════════════╗
-- ║ SECURITY-FINDING #3 — auth.uid() USED AS tenant_id ON    ║
-- ║ THREE TABLES (Pattern 3 bug)                             ║
-- ╠══════════════════════════════════════════════════════════╣
-- ║ The following three tables use `auth.uid()` as the       ║
-- ║ tenant-isolation check, instead of a JWT claim or        ║
-- ║ session variable:                                        ║
-- ║                                                          ║
-- ║  1. brand_content_log                                    ║
-- ║     policy: "Tenant brand content log" / ALL / {public}  ║
-- ║     using:  ((tenant_id = auth.uid()) OR                 ║
-- ║              EXISTS (SELECT 1 FROM tenants               ║
-- ║               WHERE tenants.id = brand_content_log       ║
-- ║                                     .tenant_id))         ║
-- ║                                                          ║
-- ║  2. storefront_component_presets                         ║
-- ║     policy: "Tenant or global presets visible" / SELECT  ║
-- ║     using:  ((tenant_id IS NULL) OR                      ║
-- ║              (tenant_id = auth.uid()))                   ║
-- ║     (also: "Tenant can manage own presets" / ALL /       ║
-- ║      using (tenant_id IS NOT NULL) — equally permissive) ║
-- ║                                                          ║
-- ║  3. storefront_page_tags                                 ║
-- ║     policy: "Tenant page tags" / ALL / {public}          ║
-- ║     using:  ((tenant_id = auth.uid()) OR                 ║
-- ║              EXISTS (SELECT 1 FROM tenants               ║
-- ║               WHERE tenants.id = storefront_page_tags    ║
-- ║                                     .tenant_id))         ║
-- ║                                                          ║
-- ║ WHY THIS IS A BUG: auth.uid() returns the signed-in      ║
-- ║ Supabase user UUID, not the Optic Up tenant UUID. The    ║
-- ║ check `tenant_id = auth.uid()` is therefore comparing    ║
-- ║ a tenant id against a user id — they are distinct        ║
-- ║ namespaces and will almost never match. The secondary    ║
-- ║ EXISTS-over-tenants clause in #1 and #3 additionally     ║
-- ║ matches ANY row whose tenant_id points at any existing   ║
-- ║ tenant, i.e. it resolves to "true" in every real row,    ║
-- ║ which nullifies isolation entirely.                      ║
-- ║                                                          ║
-- ║ Why this has not caused an incident yet: writes to       ║
-- ║ these three tables currently go through service_role     ║
-- ║ code paths only (Storefront Studio admin + brand content ║
-- ║ generator), and service_role bypasses RLS. The broken    ║
-- ║ isolation is latent until a public-facing write path     ║
-- ║ is added to any of these tables.                         ║
-- ║                                                          ║
-- ║ Policy text: db-audit/04-policies.md lines 22-24         ║
-- ║              (brand_content_log),                        ║
-- ║              lines 125-126 (storefront_component_presets)║
-- ║              lines 136-138 (storefront_page_tags)        ║
-- ║ Remediation: tracked in MASTER_ROADMAP.md under          ║
-- ║              Module 3 Phase B preamble checklist.        ║
-- ╚══════════════════════════════════════════════════════════╝

-- MINOR OUTLIER (not a security finding):
--   public.tenant_config.tenant_config_tenant_read uses `::jsonb` cast,
--   while every other JWT-based policy uses `::json`. Both work — pg
--   casts text to either. Flagged here only so a future migration sweep
--   picks it up. See db-audit/04-policies.md line 169.


-- ============================================================
-- FUNCTIONS (72 total in public schema)
-- Full list with signatures: db-audit/05-functions.md.
-- Split into two subsections: project code vs extension noise.
-- Function BODIES are not exposed by information_schema; verifying
-- implementation details (FOR UPDATE, SECURITY DEFINER logic, etc.)
-- is SEPARATE WORK, not performed by this audit.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Project functions (41) — plpgsql / sql, Optic Up code
-- ------------------------------------------------------------

--   Tenant lifecycle (Module 2 — Platform Admin):
--     activate_tenant(p_tenant_id, p_admin_id) -> void
--     create_tenant(p_name, p_slug, p_owner_name, p_owner_email,
--                   p_owner_phone, p_plan_id, p_admin_pin, p_admin_name,
--                   p_created_by) -> uuid
--     delete_tenant(p_tenant_id, p_deleted_by) -> void
--     suspend_tenant(p_tenant_id, p_reason, p_admin_id) -> void
--     update_tenant(p_tenant_id, p_updates, p_admin_id) -> void
--     get_all_tenants_overview() -> jsonb
--     get_tenant_activity_log(...) -> jsonb
--     get_tenant_employees(p_tenant_id) -> jsonb
--     get_tenant_stats(p_tenant_id) -> jsonb
--     validate_slug(p_slug) -> jsonb
--
--   Plan / feature gates:
--     check_plan_limit(p_tenant_id, p_resource) -> jsonb
--     is_feature_enabled(p_tenant_id, p_feature) -> boolean
--     is_platform_super_admin() -> boolean
--
--   Inventory (atomic writes — Iron Rule #1 atomicity):
--     decrement_inventory(inv_id, delta) -> void
--     increment_inventory(inv_id, delta) -> void
--     set_inventory_qty(inv_id, new_qty) -> void
--     apply_stock_count_delta(p_inventory_id, p_counted_qty, p_tenant_id,
--                             p_user_id, p_count_id) -> json
--     get_low_stock_brands() -> TABLE(...)
--
--   Sequential number generators (Iron Rule #13):
--     next_box_number(p_tenant_id uuid) -> text
--     next_internal_doc_number(p_tenant_id uuid, p_prefix text) -> text
--     next_po_number(p_tenant_id uuid, p_supplier_number text) -> text
--     next_return_number(p_tenant_id uuid, p_supplier_number text) -> text
--     NOTE: information_schema does not expose function bodies, so this
--     audit does NOT confirm FOR UPDATE locking. Verifying Iron Rule #13
--     compliance is a separate task tracked outside Phase 3A.
--
--   Shipments / debt / payments:
--     increment_shipment_counters(p_shipment_id, p_items_delta,
--                                 p_value_delta) -> void
--     increment_paid_amount(p_doc_id, p_delta) -> void
--     increment_prepaid_used(p_deal_id, p_delta) -> void
--     get_po_aggregates(p_tenant_id) -> TABLE(po_id, item_count, total_value)
--
--   Auth:
--     reset_employee_pin(p_tenant_id, p_employee_id, p_new_pin,
--                        p_must_change, p_admin_id) -> void
--
--   Alerts:
--     generate_daily_alerts(p_tenant_id) -> json
--
--   Storefront leads / content / translations (Module 3):
--     submit_storefront_lead(p_tenant_id, p_inventory_id, p_contact_type,
--                            p_contact_value) -> uuid
--     create_translated_page(p_tenant_id, p_source_page_id, p_target_lang,
--                            p_translated_blocks, p_title, p_slug,
--                            p_meta_title, p_meta_description) -> uuid
--     mark_translations_stale(p_page_id, p_changed_blocks) -> integer
--     get_translation_context(p_tenant_id, p_target_lang, p_limit) -> jsonb
--     save_translation_memory_batch(p_entries jsonb) -> void            -- overload #1
--     save_translation_memory_batch(p_tenant_id, p_entries) -> integer  -- overload #2
--     promote_to_platform(p_memory_ids uuid[]) -> integer
--
--   OCR templates:
--     update_ocr_template_stats(p_tenant_id, p_supplier_id, p_doc_type_code,
--                               p_was_corrected, p_new_hints) -> json     -- overload #1
--     update_ocr_template_stats(p_tenant_id, p_supplier_id, p_doc_type_code,
--                               p_was_corrected, p_new_hints,
--                               p_fields_suggested, p_fields_accepted) -> json   -- overload #2
--
--   Triggers (trigger functions, no direct call):
--     save_previous_blocks() -> trigger
--     update_storefront_components_updated_at() -> trigger
--     update_storefront_pages_updated_at() -> trigger
--     update_storefront_reviews_updated_at() -> trigger
--     update_updated_at() -> trigger

-- ------------------------------------------------------------
-- 2. Extension functions (31) — pg_trgm, NOT Optic Up code
-- ------------------------------------------------------------
-- Installed automatically by `CREATE EXTENSION pg_trgm`. Language `c`,
-- IMMUTABLE volatility, not security definer. Managed by the extension.
-- These appear in db-audit/05-functions.md only because the audit query
-- scans all functions in the public schema. Do NOT document them here.
-- Full list: db-audit/05-functions.md rows where language = 'c'.
--
-- Family summary:
--   GiST operator-class support:
--     gtrgm_in, gtrgm_out, gtrgm_compress, gtrgm_decompress,
--     gtrgm_consistent, gtrgm_distance, gtrgm_options,
--     gtrgm_penalty, gtrgm_picksplit, gtrgm_same, gtrgm_union
--   GIN operator-class support:
--     gin_extract_query_trgm, gin_extract_value_trgm,
--     gin_trgm_consistent, gin_trgm_triconsistent
--   Similarity scalars & operators:
--     similarity, similarity_dist, similarity_op, show_trgm,
--     word_similarity, word_similarity_commutator_op,
--     word_similarity_dist_commutator_op, word_similarity_dist_op,
--     word_similarity_op, strict_word_similarity,
--     strict_word_similarity_commutator_op,
--     strict_word_similarity_dist_commutator_op,
--     strict_word_similarity_dist_op, strict_word_similarity_op,
--     set_limit, show_limit


-- ============================================================
-- SEQUENCES
-- ============================================================
-- No Postgres sequences exist in the public schema (confirmed 2026-04-11
-- via pg_sequences query — see db-audit/06-sequences.md). This is a
-- deliberate architectural choice, not a gap:
--
--   * All primary keys use UUIDs (gen_random_uuid / uuid_generate_v4).
--   * All human-readable sequential numbers (PO, return, box, internal
--     doc) are generated by SECURITY DEFINER RPCs. See the
--     `next_*_number` entries in the FUNCTIONS section above and the
--     signatures in db-audit/05-functions.md.
--   * Iron Rule #13 requires that these RPCs use `FOR UPDATE` locking
--     internally. Verifying that the actual function bodies comply is
--     SEPARATE WORK and is NOT confirmed by this audit — information_schema
--     does not expose function bodies.
--
-- If a future migration ever adds a CREATE SEQUENCE to public, update
-- this section and file a follow-up to reassess the RPC-only pattern.

-- ═══════════════════════════════════════════════════════════════
-- End of GLOBAL_SCHEMA.sql
-- ═══════════════════════════════════════════════════════════════
